### ISSUE TITLE
TypeError: an integer is required(got type bytes)

### ISSUE THREAD

**Issue by LaRevoltage** [kalliope-project/kalliope_starter_en#7]
root@kali:/kalliope_starter_en# kalliope start                     Starting REST API Listening port: 5000                             Starting Kalliope                                                  Press Ctrl+C for stopping
Starting order signal
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/trigger/snowboy/snowboydetect.py", line 26, in swig_import_helper
    fp, pathname, description = imp.find_module(module_file_path, [dirname(__file__)])
  File "/usr/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'aarch64/python38/_snowboydetect'

During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/signals/order/order.py", line 89, in run
    self.start_trigger()
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 390, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 1127, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 408, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 417, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 269, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 279, in _change_state
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/core/RestAPI/FlaskAPI.py", line 81, in run
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 121, in enter
    http_server.serve_forever()
  File "/usr/lib/python3/dist-packages/gevent/baseserver.py", line 367, in serve_forever
    event_data.machine.callbacks(self.on_enter, event_data)
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 1049, in callbacks
    self.start()
  File "/usr/lib/python3/dist-packages/gevent/baseserver.py", line 305, in start
    self.callback(func, event_data)
  File "/usr/local/lib/python3.8/dist-packages/transitions-0.8.2-py3.8.egg/transitions/core.py", line 1070, in callback
    self.init_socket()
  File "/usr/lib/python3/dist-packages/gevent/pywsgi.py", line 1491, in init_socket
    self.update_environ()
    func(*event_data.args, **event_data.kwargs)
  File "/usr/lib/python3/dist-packages/gevent/pywsgi.py", line 1503, in update_environ
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/signals/order/order.py", line 96, in start_trigger_process
    self.trigger_instance = TriggerLauncher.get_trigger(settings=self.settings, callback=self.trigger_callback)
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/core/TriggerLauncher.py", line 32, in get_trigger
    name = socket.getfqdn(address[0])
    trigger_instance = Utils.get_dynamic_class_instantiation(package_name="trigger",
  File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 269, in getfqdn
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/core/Utils/Utils.py", line 126, in get_dynamic_class_instantiation
    hostname, aliases, _ = gethostbyaddr(name)
  File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 241, in gethostbyaddr
    mod = __import__(package_path, fromlist=[module_name.capitalize()])
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/trigger/snowboy/__init__.py", line 1, in <module>
    return get_hub().resolver.gethostbyaddr(ip_address)
    from .snowboy import Snowboy
  File "/usr/lib/python3/dist-packages/gevent/resolver/thread.py", line 68, in gethostbyaddr
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/trigger/snowboy/snowboy.py", line 6, in <module>
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "/usr/lib/python3/dist-packages/gevent/pool.py", line 159, in apply
    from kalliope.trigger.snowboy import snowboydecoder
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/trigger/snowboy/snowboydecoder.py", line 7, in <module>
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
    from . import snowboydetect
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/trigger/snowboy/snowboydetect.py", line 36, in <module>
    _snowboydetect = swig_import_helper()
  File "/usr/local/lib/python3.8/dist-packages/kalliope-0.7.0-py3.8.egg/kalliope/trigger/snowboy/snowboydetect.py", line 28, in swig_import_helper
    import _snowboydetect
ModuleNotFoundError: No module named '_snowboydetect'
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
So, what should i do?
using lastest kali

**Comment by Sispheor** [comment]
On which machine are you?
It's not supported.
aarch64/python38/_snowboydetect.

**Comment by LaRevoltage** [comment]
Oh, okay, I will use rpi than(thought before installing I could check it)
